name: widget-server pipe DockerHub

on: 
  push:
    braches: 
    #  // pode aplicar a regrar a v치rias branches
      - 'main'

# pode ter v치rios jobs
jobs:
  Build:
    name: Build
    # pipe geralmente roda em cima de linux
    runs-on: ubuntu-latest
    # o job pode ter v치rias etapas
    steps:
        # identifica o que essa etapa faz
      - name: Checkout
        id: checkout
        # esta usando uma add-on para fazer o checkout para n칩s
        uses: actions/checkout@v4
      
      - name: Login to DocjerHub
        id: login-docker-DocjerHubuses:docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN}}

      - name: Generate tag
        id: generate_tag
        # GITHUB_SHA - pega o hash do commit  do commit
        # $GITHUB_SHA | head -c7 - faz com que pegue os 7 primeiros caracteres da hash do commit 
        # "sha=$SHA" >> $GITHUB_OUTPUT estou colocando o valor de $SHA na variavel sha e colocando no output do github
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build and push image to AWS ECR
        id: build-push-image
        env:
          DOCKERHUB_REPOSITORY: ${{ vars.DOCKERHUB_REPOSITORY }}
          IMAGE_TAG: ${{ steps.generate_tag.outputs.sha }}
        # executa dentro da nossa iamgem
        # o pipe (|) permite executar mais de um comando
        run: | 
          docker build -t $DOCKERHUB_REPOSITORY:$IMAGE_TAG .
          docker push $DOCKERHUB_REPOSITORY:$IMAGE_TAG