name: widget-server pipe

on: 
  push:
    braches: 
    #  // pode aplicar a regrar a v치rias branches
      - 'main'
env:
  CONTAINER_REPOSITORY: 'rocketseat/widget-server'

# pode ter v치rios jobs
jobs:
  Build:
    name: Build
    # pipe geralmente roda em cima de linux
    runs-on: ubuntu-latest
    # o job pode ter v치rias etapas
    steps:
        # identifica o que essa etapa faz
      - name: Checkout
        id: checkout
        # esta usando uma add-on para fazer o checkout para n칩s
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
      # pego no marktplace do github
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate tag
        id: generate_tag
        # GITHUB_SHA - pega o hash do commit  do commit
        # $GITHUB_SHA | head -c7 - faz com que pegue os 7 primeiros caracteres da hash do commit 
        # "sha=$SHA" >> $GITHUB_OUTPUT estou colocando o valor de $SHA na variavel sha e colocando no output do github
        run: |
          SHA=${ECHO $GITHUB_SHA | head -c7}
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build and push image to AWS ECR
        id: build-push-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ steps.generate_tag.outputs.sha }}
        # executa dentro da nossa iamgem
        # o pipe (|) permite executar mais de um comando
        run: | 
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG