name: widget-server pipe

on: 
  push:
    braches: 
    #  // pode aplicar a regrar a v치rias branches
      - 'main'

# pode ter v치rios jobs
jobs:
  Build:
    name: Build
    # pipe geralmente roda em cima de linux
    runs-on: ubuntu-latest
    # o job pode ter v치rias etapas
    steps:
        # identifica o que essa etapa faz
      - name: Checkout
        # esta usando uma add-on para fazer o checkout para n칩s
        uses: actions/checkout@v4